option("profiling","F")
option("debuginfo","F")   
option("optimization","T")   
option("internal_backend","T")
option("keep_files","F")
import("libm3")
module("Blowfish")   
implementation ("BlowfishTest")   
program ("blowfish")
